"""Rich seed data for The Notice Board — South African opportunity ecosystem."""
from datetime import datetime, timedelta, timezone


def _iso_offset(days: int) -> str:
    return (datetime.now(timezone.utc) + timedelta(days=days)).date().isoformat()


OPPORTUNITIES = [
    {
        "id": "opp-001",
        "title": "Software Engineering Graduate Programme 2027",
        "organisation": "TechCorp SA",
        "category": "internship",
        "subcategory": "Graduate Programme",
        "location": "Sandton",
        "province": "Gauteng",
        "remote": False,
        "employment_type": "Full-time",
        "experience_level": "Entry Level",
        "salary": "R18,000 – R25,000 / month stipend",
        "closing_date": _iso_offset(21),
        "posted_date": _iso_offset(-2),
        "description": "Join our cutting-edge software engineering team as a graduate. Undertake a 12-month intensive training programme covering full-stack web development, cloud infrastructure, and AI integration. A structured pathway into a permanent role.",
        "requirements": ["BSc / BEng in Computer Science or related", "0–1 year experience", "Passion for building", "Strong problem-solving"],
        "responsibilities": ["Ship features across the stack", "Pair with senior engineers", "Attend structured learning tracks"],
        "benefits": ["Mentorship", "Cloud certifications sponsored", "Health cover", "Permanent conversion track"],
        "application_instructions": "Submit CV, academic transcript, and a short cover letter via the application portal.",
        "application_url": "https://example.com/apply/techcorp",
        "source_url": "https://example.com/techcorp",
        "source_type": "official",
        "verification_status": "verified",
        "verified_date": _iso_offset(-1),
        "featured": True,
        "tags": ["Software", "Graduate", "Full-stack", "Cloud"],
        "industry": "Technology",
        "match_score": 92,
    },
    {
        "id": "opp-002",
        "title": "Municipal Infrastructure Tender — Road Resurfacing",
        "organisation": "City of Tshwane",
        "category": "tender",
        "subcategory": "Construction",
        "location": "Pretoria",
        "province": "Gauteng",
        "remote": False,
        "employment_type": "Contract",
        "experience_level": "Business",
        "salary": "R12M – R18M estimated value",
        "closing_date": _iso_offset(3),
        "posted_date": _iso_offset(-1),
        "description": "The City of Tshwane invites bids for the resurfacing of major arterial roads in the CBD. CIDB grading 4CE or higher required. Compulsory site briefing.",
        "requirements": ["CIDB 4CE or higher", "Valid tax clearance", "BBBEE certificate", "3+ years municipal works"],
        "responsibilities": ["Site preparation", "Milling and asphalt overlay", "Traffic management plan", "Quality assurance"],
        "benefits": [],
        "application_instructions": "Collect bid documents from the Municipal Office. Compulsory briefing at 10am.",
        "reference_number": "COT-2027-INF-042",
        "briefing_date": _iso_offset(1),
        "source_type": "official",
        "verification_status": "verified",
        "verified_date": _iso_offset(0),
        "featured": True,
        "tags": ["Construction", "Municipal", "Roads", "CIDB"],
        "industry": "Construction",
        "match_score": 78,
    },
    {
        "id": "opp-003",
        "title": "Remote Customer Service Agent",
        "organisation": "Global Support Services",
        "category": "job",
        "subcategory": "Customer Service",
        "location": "Remote",
        "province": "Nationwide",
        "remote": True,
        "employment_type": "Full-time",
        "experience_level": "Entry Level",
        "salary": "R9,500 – R12,000 / month",
        "closing_date": _iso_offset(0),
        "posted_date": _iso_offset(-10),
        "description": "Handle inbound customer inquiries via chat and email. Must have stable fibre internet and backup power. Rotating shifts.",
        "requirements": ["Matric certificate", "Stable fibre / LTE", "UPS or backup power", "Fluent English"],
        "responsibilities": ["Respond to customer chats & emails", "Escalate complex cases", "Meet CSAT and response-time SLAs"],
        "benefits": ["Fully remote", "Medical aid", "Data allowance"],
        "application_url": "https://example.com/apply/gss",
        "source_type": "verified",
        "verification_status": "verified",
        "featured": False,
        "tags": ["Remote", "Customer Service", "No degree"],
        "industry": "BPO",
        "match_score": 88,
    },
    {
        "id": "opp-004",
        "title": "Junior Artisan Apprenticeship (Electrical)",
        "organisation": "Eskom",
        "category": "apprenticeship",
        "subcategory": "Electrical",
        "location": "Witbank",
        "province": "Mpumalanga",
        "remote": False,
        "employment_type": "Fixed term",
        "experience_level": "No Experience",
        "salary": "R7,200 / month stipend",
        "closing_date": _iso_offset(5),
        "posted_date": _iso_offset(-1),
        "description": "3-year electrical apprenticeship programme. Successful candidates will qualify as Red Seal artisans.",
        "requirements": ["N2 Electrical (or Grade 12 with Maths & Science)", "SA citizen", "Medically fit", "Willing to relocate"],
        "responsibilities": ["Assist qualified artisans", "Attend TVET training blocks", "Complete workplace logbook"],
        "benefits": ["Trade certification", "Permanent conversion possible", "PPE provided"],
        "reference_number": "ESK-APP-2027-EL-118",
        "source_type": "official",
        "verification_status": "verified",
        "featured": True,
        "tags": ["Apprenticeship", "Trade", "Red Seal", "Electrical"],
        "industry": "Energy",
        "match_score": 74,
    },
    {
        "id": "opp-005",
        "title": "Digital Marketing Learnership (SETA-Accredited)",
        "organisation": "Growth Media",
        "category": "learnership",
        "subcategory": "Digital Marketing",
        "location": "Cape Town",
        "province": "Western Cape",
        "remote": True,
        "employment_type": "Learnership",
        "experience_level": "No Experience",
        "salary": "R4,500 / month stipend",
        "closing_date": _iso_offset(2),
        "posted_date": _iso_offset(-5),
        "description": "A 12-month SETA-accredited learnership in Digital Marketing. Earn a stipend while learning SEO, paid media, and content creation. NQF Level 5 qualification on completion.",
        "requirements": ["Matric with English HL", "18–35 years", "SA citizen", "Basic laptop & internet"],
        "responsibilities": ["Attend virtual lectures", "Complete portfolio of evidence", "Assist live client campaigns"],
        "benefits": ["NQF Level 5 certificate", "Portfolio-based work experience", "Placement support"],
        "source_type": "verified",
        "verification_status": "verified",
        "featured": False,
        "tags": ["Learnership", "Digital Marketing", "Remote", "Youth"],
        "industry": "Marketing",
        "match_score": 85,
    },
    {
        "id": "opp-006",
        "title": "Chartered Accountancy Bursary Programme",
        "organisation": "SAICA & Partner Firms",
        "category": "bursary",
        "subcategory": "Finance",
        "location": "Johannesburg",
        "province": "Gauteng",
        "remote": False,
        "employment_type": "Full-time study",
        "experience_level": "No Experience",
        "salary": "Full tuition + book allowance + laptop",
        "closing_date": _iso_offset(14),
        "posted_date": _iso_offset(-3),
        "description": "Full-cost CA(SA) bursary covering three years of undergraduate study plus vacation work. Guaranteed articles placement upon completion.",
        "requirements": ["Grade 12 with Maths (70%+)", "Accepted into a SAICA-accredited BCom", "SA citizen", "Financial need"],
        "responsibilities": ["Maintain 60% average", "Complete vacation work", "Sign work-back agreement"],
        "benefits": ["Full tuition", "Accommodation", "Laptop", "Guaranteed articles"],
        "source_type": "official",
        "verification_status": "verified",
        "featured": True,
        "tags": ["Bursary", "CA(SA)", "Finance", "Full cost"],
        "industry": "Finance",
        "match_score": 90,
    },
    {
        "id": "opp-007",
        "title": "Senior Data Analyst",
        "organisation": "Standard Bank",
        "category": "job",
        "subcategory": "Data & Analytics",
        "location": "Rosebank",
        "province": "Gauteng",
        "remote": False,
        "employment_type": "Full-time",
        "experience_level": "Mid Level",
        "salary": "R55,000 – R75,000 / month",
        "closing_date": _iso_offset(9),
        "posted_date": _iso_offset(-4),
        "description": "Drive analytics for retail banking products. Build dashboards, run experiments, and partner with product & risk teams.",
        "requirements": ["3+ years SQL", "Python or R", "BI tools (Power BI / Tableau)", "Banking or fintech domain"],
        "responsibilities": ["Design experiments", "Own reporting stack", "Present findings to leadership"],
        "benefits": ["Medical aid", "Retirement", "Study allowance"],
        "source_type": "official",
        "verification_status": "verified",
        "featured": False,
        "tags": ["Data", "SQL", "Python", "Banking"],
        "industry": "Financial Services",
        "match_score": 82,
    },
    {
        "id": "opp-008",
        "title": "Enterprise Development Fund — SMME Supplier Programme",
        "organisation": "Department of Small Business Development",
        "category": "business",
        "subcategory": "Funding",
        "location": "Nationwide",
        "province": "Nationwide",
        "remote": False,
        "employment_type": "Grant",
        "experience_level": "Business",
        "salary": "R250,000 – R2,500,000 grant",
        "closing_date": _iso_offset(28),
        "posted_date": _iso_offset(-7),
        "description": "Non-repayable grant for majority black-owned SMMEs in manufacturing, agro-processing and green economy sectors. Includes mentorship.",
        "requirements": ["Registered CIPC entity", "12+ months trading history", "51%+ black ownership", "Turnover under R10M"],
        "responsibilities": ["Attend business support sessions", "Submit quarterly milestones", "Job creation targets"],
        "benefits": ["Non-repayable grant", "Mentorship", "Market access support"],
        "reference_number": "DSBD-EDF-2027-Q1",
        "source_type": "official",
        "verification_status": "verified",
        "featured": True,
        "tags": ["Funding", "Grant", "SMME", "Government"],
        "industry": "Enterprise Development",
        "match_score": 70,
    },
    {
        "id": "opp-009",
        "title": "Registered Nurse — Trauma Unit",
        "organisation": "Life Healthcare",
        "category": "job",
        "subcategory": "Healthcare",
        "location": "Durban",
        "province": "KwaZulu-Natal",
        "remote": False,
        "employment_type": "Full-time",
        "experience_level": "Mid Level",
        "salary": "R32,000 – R42,000 / month",
        "closing_date": _iso_offset(11),
        "posted_date": _iso_offset(-2),
        "description": "Registered nurse required for a busy trauma unit. Rotating 12-hour shifts. ACLS and BLS certification advantageous.",
        "requirements": ["SANC registration", "BLS certified", "3+ years acute-care experience"],
        "responsibilities": ["Triage & stabilisation", "Emergency interventions", "Handover to admitting teams"],
        "benefits": ["Shift allowance", "Medical aid", "CPD funding"],
        "source_type": "official",
        "verification_status": "verified",
        "featured": False,
        "tags": ["Nursing", "Trauma", "Healthcare"],
        "industry": "Healthcare",
        "match_score": 65,
    },
    {
        "id": "opp-010",
        "title": "Request for Quotation — Office Catering (12 Months)",
        "organisation": "Provincial Treasury: Western Cape",
        "category": "rfq",
        "subcategory": "Food & Catering",
        "location": "Cape Town",
        "province": "Western Cape",
        "remote": False,
        "employment_type": "Contract",
        "experience_level": "Business",
        "salary": "R800,000 estimated",
        "closing_date": _iso_offset(6),
        "posted_date": _iso_offset(-2),
        "description": "RFQ for daily office catering including tea/coffee stations, breakfast platters, and event catering. 12-month contract with 6-month optional extension.",
        "requirements": ["CSD registered", "Food safety certification", "3 traceable references", "BBBEE Level 4 or better"],
        "responsibilities": ["Daily deliveries", "Event catering on request", "Cold-chain compliance"],
        "benefits": [],
        "reference_number": "WCPT-RFQ-2027-14",
        "source_type": "official",
        "verification_status": "verified",
        "featured": False,
        "tags": ["RFQ", "Catering", "Provincial"],
        "industry": "Hospitality",
        "match_score": 60,
    },
    {
        "id": "opp-011",
        "title": "Coding Bootcamp Scholarship (Full Ride)",
        "organisation": "WeThinkCode_",
        "category": "skills",
        "subcategory": "Software Development",
        "location": "Johannesburg / Cape Town",
        "province": "Gauteng",
        "remote": False,
        "employment_type": "Full-time study",
        "experience_level": "No Experience",
        "salary": "Fully funded",
        "closing_date": _iso_offset(18),
        "posted_date": _iso_offset(-6),
        "description": "24-month fully-funded peer-learning software engineering programme. No prior coding experience needed. Selection via logic-based online tests.",
        "requirements": ["17–35 years", "Matric", "Not currently studying", "SA citizen or permanent resident"],
        "responsibilities": ["Complete peer projects", "Attend campus daily", "Complete internships between years"],
        "benefits": ["No fees", "Employability outcomes 95%+", "Internship placement"],
        "source_type": "official",
        "verification_status": "verified",
        "featured": True,
        "tags": ["Skills", "Coding", "Fully funded", "Youth"],
        "industry": "Education",
        "match_score": 93,
    },
    {
        "id": "opp-012",
        "title": "Government Communications Officer",
        "organisation": "GCIS (Government Communication)",
        "category": "government",
        "subcategory": "Communications",
        "location": "Pretoria",
        "province": "Gauteng",
        "remote": False,
        "employment_type": "Permanent",
        "experience_level": "Mid Level",
        "salary": "R376,596 – R443,601 (Level 8)",
        "closing_date": _iso_offset(12),
        "posted_date": _iso_offset(-3),
        "description": "Support internal and external communication for national departments. Draft speeches, media statements and manage digital channels.",
        "requirements": ["3-year degree in Communications/Journalism", "3+ years experience", "Public sector experience advantageous"],
        "responsibilities": ["Media liaison", "Content production", "Event support"],
        "benefits": ["Government benefits", "Housing allowance", "Pension"],
        "reference_number": "GCIS-2027-COM-08",
        "source_type": "official",
        "verification_status": "verified",
        "featured": False,
        "tags": ["Government", "Communications", "Public sector"],
        "industry": "Government",
        "match_score": 68,
    },
]
